sudo: false
language: ruby
deploy:
  provider: heroku
  api_key:
    secure: B54voqXffIckJlMgFOIrtq1PeSDOfm1OdgG6hwRv7I94dVFb/tmWiT1W6/9g1NOTatJsfyrfpmpJ6N/2bPjel6Fjbdef2Ih6dyMmnIhLCpZWy/5WOjgLWYHdnWtODrXAqEsmkxiAjmSCCoWfEjwDzLPE3TxYGR7Yeqz5RQsFFLE=
  run:
    - "rake db:migrate"
before_script:
  - psql -c 'create database bongloy_demo_test;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
