# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  prefill_email: <%= ENV["PREFILL_EMAIL"] %>
  require_address: <%= ENV["REQUIRE_ADDRESS"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  bongloy_charges_url: <%= ENV["BONGLOY_CHARGES_URL"] %>
  bongloy_test_account_email: <%= ENV["BONGLOY_TEST_ACCOUNT_EMAIL"] %>
  bongloy_test_account_password: <%= ENV["BONGLOY_TEST_ACCOUNT_PASSWORD"] %>
  bongloy_default_js_url: <%= ENV["BONGLOY_DEFAULT_JS_URL"] %>
  bongloy_checkout_default_js_url: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_JS_URL"] %>
  bongloy_default_publishable_key: <%= ENV["BONGLOY_DEFAULT_PUBLISHABLE_KEY"] %>
  bongloy_checkout_default_image_url: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_IMAGE_URL"] %>
  bongloy_checkout_default_name: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_NAME"] %>
  bongloy_checkout_default_description: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_DESCRIPTION"] %>
  bongloy_checkout_default_label: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_LABEL"] %>
  bongloy_checkout_default_amount: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_AMOUNT"] %>
  bongloy_checkout_default_currency: <%= ENV["BONGLOY_CHECKOUT_DEFAULT_CURRENCY"] %>

development:
  <<: *production
  secret_key_base: ffbedb934c2a66e431252427e9f9c8ca1ffbf086638da08134d0144ce49c2ae7d214060303aca459d214c4056499fc97d7c8f5008ff1d028ed7f13fd70d73a20

test:
  secret_key_base: d52c83db70f65538b687877ad13bed08bf3f80d5ea4a129d192c6ef9ec1863d480da4b17a2c015b5f9db545494b529e48db4a728b03b823b15e83ded30ff745e
